//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DVHC
    {
        public DVHC()
        {
            this.Users = new HashSet<User>();
        }
    
        public int IDDVHC { get; set; }
        public string TenDVHC { get; set; }
        public string MoTaDVHC { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ParentID { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
