//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppCore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<int> IDRole { get; set; }
        public Nullable<int> IDDVHC { get; set; }
        public Nullable<int> Status { get; set; }
        public string FullName { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public Nullable<int> IDTinh { get; set; }
        public Nullable<int> IDHuyen { get; set; }
        public Nullable<int> IDXa { get; set; }
    
        public virtual DVHC DVHC { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
